# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
    name: LinuxBuild2

steps:
- checkout: self
  clean: true
  fetchTags: false
- task: Bash@3
  displayName: 'apt update'
  continueOnError: True
  inputs:
    targetType: inline
    script: >-
      sudo apt-get update
    failOnStderr: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: Bash@3
  displayName: 'Quality Gate with PSSCript Analyzer for Errors '
  continueOnError: False
  inputs:
    targetType: inline
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
    script: >-

        pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force"
        
        pwsh -Command "Import-Module -Name PSScriptAnalyzer"

        pwsh -Command "Invoke-ScriptAnalyzer -Path ./WinDesktopBasicSetup.ps1 -Profile ./PSAnalyzerProfileError.txt -Recurse"

    failOnStderr: true
- task: Bash@3
  displayName: 'Analyze with PSSCript Analyzer'
  continueOnError: True
  inputs:
    targetType: inline
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
    script: >-

        pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force"
        
        pwsh -Command "Import-Module -Name PSScriptAnalyzer"

        pwsh -Command "Invoke-ScriptAnalyzer ./WinDesktopBasicSetup.ps1 | Select-Object Severity, Line, Message, RuleName | Format-List"

    failOnStderr: true

- task: Bash@3
  displayName: 'Analyze with Injection Hunter'
  continueOnError: True
  inputs:
    targetType: inline
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
    script: >-

        pwsh -Command "Install-Module -Name InjectionHunter -Force"
        
        pwsh -Command "Import-Module -Name InjectionHunter"

        pwsh -Command "Invoke-ScriptAnalyzer ./WinDesktopBasicSetup.ps1 -CustomRulePath (Get-Module InjectionHunter -List | % Path) -v | Format-List"

    failOnStderr: true
- task: Bash@3
  displayName: 'Publish to Powershell Gallery'
  continueOnError: False
  inputs:
    targetType: inline
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
    script: >-
        pwsh -Command "Publish-Script -Path .\WinDesktopBasicSetup.ps1 -NuGetApiKey $(NugetAPIKey)"

    failOnStderr: true
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**/**'
    RemoveDotFiles: true